### ISSUE TITLE
What do each column in files gene_names_df and intron_df represent

### ISSUE THREAD

**Issue by ZFF00** [churchmanlab/splicing_order#1]
Dear author,
Hello, I couldn't get through the code when I reproduced your research again. I am not sure what the columns in two files are, namely "gene_name" and "gene_id" in the "hg38_UCSC_refGene_names.txt" file, and "intron_name" and "score" in the "NCBI_RefSeq_hg38_introns_parsed.bed" file. May I ask for "gene_name" and "gene_id" Are the IDs from the last column of the gtf file? Please let me know. Thank you!

gene_names_df="$annDir/hg38_UCSC_refGene_names.txt"   ['gene_name','gene_id']
intron_df="$annDir/NCBI_RefSeq_hg38_introns_parsed.bed"  ['chrom','start','end','intron_name','score','strand']

**Comment by kchoquet** [comment]
Hello,
For hg38_UCSC_refGene_names.txt: 
Gene_name refers to the NCBI gene symbol (e.g. _ACTB_) and gene_id refers to the corresponding NCBI transcript id (NM..., e.g. NM_001101). It was obtained from the UCSC Table Browser with the following selections:
Group: Genes and Gene Predictions
Track: NCBI RefSeq
Table: RefSeq All (ncbiRefSeq)
Output format: Selected fields from primary and related tables -> select name and name2
They should indeed be the IDs from the last column of the corresponding gtf file.
It was then filtered to include only protein-coding genes (e.g. transcripts that start with NM...). 
I've noticed that the transcript_id is in a slightly different format in a recent download compared to the one we used in the paper, so you may need to tweak the code to correctly merge this file with others using this column.

For NCBI_RefSeq_hg38_introns_parsed.bed, you can see the instructions for making that file in steps 109-112 of this protocol: https://pubmed.ncbi.nlm.nih.gov/33514943/. "Intron name" is a string that includes the transcript id, intron number (in the order of the genomic coordinates, so reversed for introns on minus strand), start coordinate and strand. "Score" is just a 0 for every line, as far as I know it's only present to keep the correct BED format.

Both files are available to download here: https://github.com/churchmanlab/nano-COP/annotation_files

Let me know if you have any other questions.

**Comment by ZFF00** [comment]
Thank you very much for your patient answer. I have understood the specific meaning of each column in these two files. In addition, there is another question: Are files "intron_df" and "intron_bed_file" the same file?

intron_df="$annDir/NCBI_RefSeq_hg38_introns_parsed.bed"
intron_bed_file="NCBI_RefSeq_hg38_introns_parsed_bedtool_for_intron_pairs.bed" # OR GENCODE V38

**Comment by kchoquet** [comment]
They are very similar, intron_bed_file is obtained from intron_df but the 4th column is only the gene name and the 5th column is the intron count. In addition, it contains only protein-coding mRNAs. They could probably be used interchangeably with a few tweaks to the code.

**Comment by ZFF00** [comment]
Thank you very much for your answer, I understand now.
